### PR TITLE
Created reservation section

### PR DESCRIPTION
**Pull request by AnnaIstochnikova**
- Google Map with geolocation of the restaurant (excluding the mobile version);
- Redirecting to the reservation page;

! One thing we need to change is the text with the description.

### CODE REVIEW

**Review by TN4HPEL3 — CHANGES_REQUESTED** [review]
Missing padding from right, left and bottom.

**Comment by AnnaIstochnikova** [comment]
@TN4HPEL3 where exactly do we need a padding?

**Comment by TN4HPEL3** [comment]
@AnnaIstochnikova I will send you screenshot on our slack.

**Comment by TN4HPEL3** [comment]
Did you implement padding as I suggest on slack? 
If not, add padding and merge ✅ 
Rest is ok 👍

**Review by TN4HPEL3 — APPROVED** [review]

**Pull request merged**
